name: Greet
on:
    push:
        branches:
            - master

jobs:
    greet:
        runs-on: ubuntu-latests
        steps:
            - name: Greet the world
              run: echo "Hello, world!"
